version: '3.9'

services:
  webgl-app:
    build: .
    container_name: webgl-app
    volumes:
      - webgl_logs:/usr/local/apache2/logs
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pw
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    secrets:
      - db_root_pw
    networks:
      - backend

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_pw
      - MYSQL_DATABASE=mydb
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - SESSION_SECRET_FILE=/run/secrets/session_secret
    secrets:
      - db_root_pw
      - session_secret
    depends_on:
      - db
    volumes:
      - auth_logs:/var/log/auth-service   # <-- volume per i log (o altri dati) del servizio
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./web_data/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - webgl-app
      - auth-service
    networks:
      - frontend
      - backend

volumes:
  webgl_logs:
  db_data:
  nginx_logs:
  auth_logs:   

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

secrets:
  db_root_pw:
    file: ./secrets/db_root_pw.txt
  session_secret:
    file: ./secrets/session_secret.txt
