FROM nginx:alpine

# 1) Copia la configurazione custom
COPY nginx.conf /etc/nginx/nginx.conf

# 2) Copia TUTTI gli asset unificati da webgl/ nella root dei file serviti
COPY webgl/ /usr/share/nginx/html/

# 3) Esponi HTTP
EXPOSE 80

# 4) Avvia Nginx in foreground
CMD ["nginx", "-g", "daemon off;"]
