version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pw
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    secrets:
      - db_root_pw
    networks:
      - backend

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_pw
      - MYSQL_DATABASE=mydb
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - SESSION_SECRET_FILE=/run/secrets/session_secret
    secrets:
      - db_root_pw
      - session_secret
    depends_on:
      - db
    volumes:
      - auth_logs:/var/log/auth-service
      - ./webgl:/usr/src/app/webgl:ro
    ports:
      - "3001:3000"
    networks:
      - backend
      - frontend

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-webgl-app:latest
    restart: unless-stopped
    networks:
      - frontend
      - backend
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-proxy
    depends_on:
      - auth-service
      - web
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

volumes:
  db_data:
  auth_logs:
  nginx_logs:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

secrets:
  db_root_pw:
    file: ./secrets/db_root_pw.txt
  session_secret:
    file: ./secrets/session_secret.txt
