AddEncoding gzip .gz

<IfModule mod_headers.c>

    <FilesMatch "\.js\.gz$">
        AddType application/javascript .gz
        Header set Content-Encoding gzip
    </FilesMatch>

    <FilesMatch "\.wasm\.gz$">
        AddType application/wasm .gz
        Header set Content-Encoding gzip
    </FilesMatch>

    <FilesMatch "\.data\.gz$">
        AddType application/octet-stream .gz
        Header set Content-Encoding gzip
    </FilesMatch>

</IfModule>
